{
 "title": "FusionPBX Incoming Calls",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Comulated incoming calls per gateway right now",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fusionpbx_individual_caller_destination_count",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Comulated incoming calls right now",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fusionpbx_total_caller_destination_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Comulated incoming calls per gateway over 1h",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fusionpbx_individual_caller_destination_count - fusionpbx_individual_caller_destination_count offset 60m",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Comulated incoming calls per gateway over grafana range",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fusionpbx_individual_caller_destination_count - fusionpbx_individual_caller_destination_count offset $__range",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Comulated incoming calls over grafana range",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fusionpbx_total_caller_destination_count - fusionpbx_total_caller_destination_count offset $__range",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Comulated incoming calls over 1h",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fusionpbx_total_caller_destination_count - fusionpbx_total_caller_destination_count offset 60m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Comulated incoming calls per gateway over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "fusionpbx_individual_caller_destination_count",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Comulated incoming calls over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "fusionpbx_total_caller_destination_count",
     "legendFormat": "incoming calls"
    }
   ]
  }
 ]
}